name: Rust static build and publish
on: ["push"]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: rexec
jobs:
  build_arch:
    name: Arch Linux package
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
#     options: --user 1001
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: ${{ env.BUILD_TARGET }}
        components: rustfmt
    - name: Install build deps
      run: |
        pacman -Syu --noconfirm rustup musl git base-devel
        rustup default stable
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
#   - name: Build ZST package
#     run: |
#       useradd -G wheel -d /rexec/ -s /bin/bash build
#       makepkg -f
    - name: LIST
      run: |
        pwd
        ls -lah

    - uses: actions/upload-artifact@v2
      name: Upload ZST package
      with:
          name: ${{ env.BINARY_NAME }}.zst
          path: rexec.*zst

