name: ARM Rust static build and publish
on: ["push"]
# push:
#   tags:
#   - '*'
#    
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: rexec
jobs:
  build:
    name: Build static binary
    runs-on: self-hosted
    container:
      image: rust:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
#     - uses: dtolnay/rust-toolchain@stable
#     - name: Build-musl
#       uses: gmiam/rust-musl-action@master
#       with:
#         args: cargo build --target $BUILD_TARGET --release
      - name: Deps
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --target ${{ env.BUILD_TARGET }} --release
          
      - name: Get version
        run: echo "VERSION=$(grep -P '^version = \"\d+\.\d+\.\d+\"' Cargo.toml | awk -F '\"' '{print $2}')" >> $GITHUB_ENV
      - name: Show version
        run:  echo ${{ env.VERSION }}
      - uses: actions/upload-artifact@v3.1.2
        name: Upload artifact
        with:
          name: ${{ env.BINARY_NAME }}_${{ env.VERSION }}_${{ env.BUILD_TARGET }}
          path: target/${{ env.BUILD_TARGET }}/release/${{ env.BINARY_NAME }}
