name: Rust-static-build-musl
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on:
  push:
    tags:
    - '*'
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: rexec
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target $BUILD_TARGET --release
    - uses: actions/upload-artifact@v2
      name: Upload artifact
      with:
        name: ${{ env.BINARY_NAME }}
        path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
    - name: Strip binary
      run: strip target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*