name: Rust-static-build-musl
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on:
  push:
    tags:
    - '*'
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: rexec
jobs:
  build:
    name: Build static binary ${{ env.BINARY_NAME }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
  release:
    name: Release binary
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/upload-artifact@v2
      name: Upload artifact
      with:
        name: ${{ env.BINARY_NAME }}
        path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}
    - uses: ncipollo/release-action@v1
      name: Update release page
      with:
        artifacts: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}
        allowUpdates: true
        body: Static build for x86_64-linux using MUSL
