name: Rust-static-build-musl
on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: rexec
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Upload artifact'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "rexec"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}